<a href="https://colab.research.google.com/github/dbstj118/2026_2-1_BDA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 패키지 numpy 개요와 자료형 ndarray

In [2]:
import numpy as np

a = np.ndarray((2,3))
a

array([[8.34887934e-316, 0.00000000e+000, 6.61216668e-310],
       [6.61216668e-310, 6.61216666e-310, 6.61218781e-310]])

In [4]:
import numpy as np

a = np.ndarray((3,2),dtype=int)
a

array([[172605268,         0],
       [172557712, 172557792],
       [172557872, 172557952]])

In [5]:
a = np.ndarray((3,2),int)
a

array([[      168983199,               0],
       [133831743583888, 133831743583936],
       [133831743072304, 133832171300272]])

#### 내장함수 array()

In [7]:
import numpy as np

a = np.array([1,2,3],dtype=int)
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [9]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [10]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


#### ndarray 특징 - 문자열 자료형

In [13]:
np.array([1,'py',3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [14]:
import numpy as np

unicode_array = np.array(['가나다','라마바','사아자'],dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [15]:
unicode_array = np.array(['가나다라마'*7,'라마바','사아자'],dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

### 내장함수 arange()와 linspace()

#### numpy.arange()

In [16]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [18]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


#### 배열의 모양을 바꿈 reshape()

In [19]:
import numpy as np

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [21]:
np.reshape(a,(3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

#### 함수 linspace(start,stop,num)

In [ ]:
import numpy as np
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [23]:
np.linspace(2,3,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [25]:
print((3-2)/(50-1))

0.02040816326530612


In [26]:
np.linspace(2.0,3.0,endpoint=False,retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [27]:
print((3-2)/50)

0.02


In [28]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [29]:
np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

In [ ]:
(3-1)/(50-1)

0.04081632653061224

In [ ]:
np.linspace(2,3,2)

array([2., 3.])

In [ ]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [ ]:
np.linspace(2,3,3,retstep = True)

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [ ]:
a = np.linspace(2,3,3,retstep = True)
a[1]

np.float64(0.5)

In [ ]:
a = np.linspace(2,3,3,retstep = True)
float(a[1])

0.5

In [ ]:
np.linspace(2,3,3,retstep = True, endpoint = False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

## numpy 주요 함수

#### zeros()

In [30]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [31]:
a.dtype

dtype('float64')

In [ ]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [32]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

#### ones()

In [33]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### numpy.eye()

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [37]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
a = np.eye(3,4,1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### numpy.full(shape,fill_value)

In [ ]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [40]:
np.full([2,3],(1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
np.full([2,3],(1,2))

ValueError: could not broadcast input array from shape (2,) into shape (2,3)

In [42]:
np.full([3,4],range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [43]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
np.full((4,3), np.arange(4).reshape(4,1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

#### numpt.empty(shape)

In [44]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [45]:
np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [46]:
np.empty([2,3],dtype=int)

array([[4611686018427387904, 4613487458278336102, 4615288898129284300],
       [4616639978017495449, 4617540697942969548, 4618441417868443647]])

#### zeros_like(a)

In [47]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

#### ones_like(a)

In [49]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

#### full_like()

In [50]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

### 배열 연산

In [51]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [52]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [54]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
b = np.full_like(a,[1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [58]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [59]:
b = np.arange(0.5,4,1)
b

array([0.5, 1.5, 2.5, 3.5])

In [60]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [61]:
b+=a
b

array([0.5, 2.5, 4.5, 6.5])

#### 2차원 배열의 곱 연산자

In [65]:
x = np.array([[1,2],[2,2],[3,2]])
x

array([[1, 2],
       [2, 2],
       [3, 2]])

In [67]:
y = np.array([[1],[1]])
y

array([[1],
       [1]])

In [68]:
x@y

array([[3],
       [4],
       [5]])

In [69]:
a = np.full((2,3),[1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [71]:
b = np.full((3,2),[2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [72]:
a@b

array([[12,  6],
       [12,  6]])

In [73]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [74]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [75]:
import numpy as np
print(np.matmul(a,b))
print(np.matmul(b,a))

[[12  6]
 [12  6]]
[[3 6 9]
 [3 6 9]
 [3 6 9]]


#### a.sum()

In [77]:
a = np.array([[10,20],[5,8],[1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [78]:
a.sum()

np.int64(46)

In [80]:
a.sum(axis=0)

array([16, 30])

In [81]:
a.sum(axis=1)

array([30, 13,  3])

In [83]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


#### a.cumsum()

In [85]:
a = np.array([[3,5,8],[1,2,3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [86]:
#일차원으로 펼쳐서 계산
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [87]:
a.cumsum(axis=0) # 시험예상, 행을 따라 세로로 합산

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [89]:
a.cumsum(axis=1) # 시험예상, 열을 따라 가로로 합산

array([[ 3,  8, 16],
       [ 1,  3,  6]])

#### 범용 함수

In [90]:
import numpy as np

a = np.array([1,4,9])
np.sqrt(a)

array([1., 2., 3.])

In [91]:
import numpy as np

a = np.array([1,4,9])
a

array([1, 4, 9])

In [92]:
b = np.full_like(a,2)
b

array([2, 2, 2])

In [93]:
np.add(a,b)

array([ 3,  6, 11])

In [94]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [95]:
np.power(a,b)

array([ 1, 16, 81])

### 배열 슬라이싱과 형태 수정

#### 1차원 배열의 첨자와 슬라이싱

In [96]:
import numpy as np

a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
print(a[3])
print(a[-2])

9
64


In [98]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [99]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [100]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [101]:
a[::-2]

array([81, 49, 25,  9,  1])

In [102]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [103]:
a[2:5] = [-5,-5,-5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81])

In [104]:
a[2:5] = [-5,-5]
a

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [105]:
a[2:5] = -10
a

array([  0,   1, -10, -10, -10,  25,  36,  49,  64,  81])

#### 2차원 배열의 첨자와 슬라이싱

In [107]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [108]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [109]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [110]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

In [111]:
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [112]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [113]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [114]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [115]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [116]:
a[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [117]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [118]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [119]:
a[2,4]

np.int64(16)

In [120]:
a[2][4]

np.int64(16)

In [121]:
a[1:3,2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [122]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [123]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [124]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [125]:
a[::-1,::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [126]:
#마지막 행과 열을 제외한 배열 반환
a[:-1,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

#### 3차원 배열의 첨자와 슬라이싱

In [128]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [129]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [130]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [131]:
a[:1,1]

array([[4, 5, 6, 7]])

In [132]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [133]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [134]:
a[1,...,1]

array([13, 17, 21])

In [135]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 1차원 배열로 만드는 ndarray.ravel()

In [137]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [138]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### np.transpose(a)와 a.transpose(), a.T

In [139]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [141]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [142]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 3차원 배열의 전치 행렬

In [143]:
b = np.arange(1,13).reshape(3,2,2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [145]:
b.T

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

### 브로드캐스팅

In [146]:
a = np.array([3,4,5])
b = np.array([8,7,6])
a+b

array([11, 11, 11])

In [147]:
a = np.array([3,4,5,7])
b = np.array([8,7,6])
a*b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [148]:
from numpy import arange
x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
y = arange(-1,2)
y

array([-1,  0,  1])

In [150]:
x*y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [151]:
x+y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [152]:
from numpy import arange

x = arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
y = arange(3,10,3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [155]:
# 소수점 이하 자릿수를 2자리로 설정
np.set_printoptions(precision=2)

In [156]:
x/y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [157]:
x-y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [158]:
from numpy import arange

x = arange(1,4)
x

array([1, 2, 3])

In [159]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [160]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [161]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [162]:
from numpy import arange
x = arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [163]:
y = arange(1,3)
y

array([1, 2])

In [164]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [165]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

#### np.newaxis

In [166]:
import numpy as np
from numpy import array

x = array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [167]:
np.newaxis is None

True

In [168]:
# 차수를 증강
a = x[None,:]
a

array([[ 0, 10, 20, 30]])

In [169]:
a = x[:,np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [170]:
from numpy import array

b = array([1,2,3])
b

array([1, 2, 3])

In [171]:
a+b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [172]:
a*b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 고급 색인

In [173]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [175]:
print(x[[2]])
print(x[[2,3]])

[2]
[2 3]


In [176]:
x[[2,3,5,8]]

array([2, 3, 5, 8])

In [177]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [ ]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [178]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [179]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [181]:
x[0,1]

np.int64(1)

In [182]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [183]:
x[,2:8]

SyntaxError: invalid syntax (1821174162.py, line 1)

In [184]:
x[[0],[1]]

array([1])

In [186]:
x[[0,1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [187]:
x[:,[5,4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [188]:
x[[1,3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [189]:
x[[1,3],:]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [185]:
x[ [2] ]

array([[16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
x[ [2,3] ]

array([2, 3])

In [ ]:
x[ 2,3 ]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
x[ [2,3,2,5,8] ]

array([2, 3, 2, 5, 8])

In [ ]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0,1]

np.int64(1)

In [ ]:
x[:,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[,2:8]

SyntaxError: invalid syntax (1821174162.py, line 1)

In [ ]:
x[...,2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0],[1] ]

array([1])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0,1] ]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[ [1,3,5] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [1,3],[2,2] ]

array([10, 26])

In [ ]:
x[ [1,3],[2,2,4] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [ ]:
x[ [1,3],[2] ]

array([10, 26])

In [ ]:
x[ [1,3],[2,3] ]

array([10, 27])

In [ ]:
x[ [0,2,4],[1] ]

array([ 1, 17, 33])

In [ ]:
x[ [0,2,4], 1 ]

array([ 1, 17, 33])

In [ ]:
x[ [0,2,4],:2 ]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[ [0,2,4],[1,1,1] ]

array([ 1, 17, 33])

In [ ]:
x[ [0,2,4],[1,1] ]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a = np.arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[[2,3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,4)][:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[np.arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[np.arange(2,4)][:,[1,1,1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [ ]:
a[np.arange(2,4)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[[2,3]][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29]])

In [ ]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[np.arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2,3,4]][:,[-1,-2,-3,-4,-5,-6,-7]]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
a[[2,3,4]][:,np.arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [190]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [191]:
# 첨자 [1,2]과 [3,2]에 해당하는 10과 26
x[[1,3],[2,2]]

array([10, 26])

In [192]:
#위와 동일
x[[1,3],[2,2]]

array([10, 26])

In [193]:
# 1,3행의 2열
x[[1,3],2]

array([10, 26])

In [194]:
x[np.array([0,2,4]),1]

array([ 1, 17, 33])

In [195]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

1
17
33


In [196]:
x[array([0,2,4]),:2]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [197]:
from numpy import array

x[array([0,2,4]),array([0,1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [199]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [200]:
a[2:4,3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [201]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [202]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [203]:
a[arange(2,4)][:,[1,0]]

array([[17, 16],
       [25, 24]])

In [204]:
a[arange(2,5)][:,[1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [205]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [206]:
a[arange(2,5)][:,arange(-1,-8,-1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

### 종료